name: update-data

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
  #schedule:
  #  - cron: "0 0 1 * *" # Runs at 00:00 UTC on the first of every month 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
        
      - name: install pipenv
        run: |
          pip install --user pipenv
          USER_BASE=`python -m site --user-base`
          echo $USER_BASE
          export PATH=$USER_BASE/bin:$PATH
          echo $PATH
          echo `which pipenv`
          echo `pwd`
        
      - name: install Python dependencies
        run: pipenv install
      
      - name: partially clone roll-wrangler MIDI and txt files
        run: |
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://github.com/pianoroll/roll-wrangler.git
          git sparse-checkout init --cone
          git sparse-checkout add "midi/exp" "midi/note" "txt"
          git checkout
          ls
          ls roll-wrangler
          echo `pwd`
        
      - name: move roll-wrangler files to expected locations
        run: |
          mv ./roll-wrangler/midi/note/*.mid midi/note/.
          mv ./roll-wrangler/midi/exp/*.mid midi/exp/.
          mv ./roll-wrangler/txt/*.txt input/txt/.
        
      - name: run the data generation script
        run: pipenv run python build-pianolatron-files.py
        
      - name: commit the new/updated output files to the repo
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: '["output/json/*.json","output/midi/*.mid","midi/exp/*.mid","midi/note/*.mid","output/catalog.json"]'
          message: 'Automatic update'
          author_name: GitHub Actions
          author_email: actions@github.com
